language: php

php:
  - 7.2
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.2
      env: PREFER_LOWEST=1 DEFAULT=0

  fast_finish: true

before_install:
  - if [[ ${TRAVIS_PHP_VERSION} != "7.4" ]]; then phpenv config-rm xdebug.ini ; fi

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction --profile
  - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-lowest --prefer-dist --no-interaction --profile -vvv; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 composer require --dev dereuromark/composer-prefer-lowest; fi

script:
  - if [[ $DEFAULT == 1 ]]; then composer validate; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then vendor/bin/validate-prefer-lowest; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
